name: Build MilkyNote Ultimate

# Kapan robot ini bekerja? Saat ada Push ke branch 'main'
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # 1. TUGAS BIKIN ANDROID APK (Jalan di Server Linux)
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Download Dependencies
        run: flutter pub get
        
      - name: Build APK
        run: flutter build apk --release
        
      - name: Upload APK ke GitHub
        uses: actions/upload-artifact@v4
        with:
          name: MilkyNote-Android
          path: build/app/outputs/flutter-apk/app-release.apk

  # 2. TUGAS BIKIN WINDOWS EXE (Jalan di Server Windows)
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Build Windows Exe
        run: |
          flutter pub get
          flutter build windows --release
          
      - name: Upload Windows ke GitHub
        uses: actions/upload-artifact@v4
        with:
          name: MilkyNote-Windows
          path: build/windows/x64/runner/Release

  # 3. TUGAS BIKIN LINUX APP (Jalan di Server Linux)
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Build Linux App
        run: |
          flutter pub get
          flutter build linux --release
          
      - name: Upload Linux ke GitHub
        uses: actions/upload-artifact@v4
        with:
          name: MilkyNote-Linux
          path: build/linux/x64/release/bundle